# Generated by Django 5.1.1 on 2024-10-03 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("test_field", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("password", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("bio", models.CharField(max_length=2048)),
                ("interests", models.CharField(max_length=2048)),
                (
                    "grad_year",
                    models.IntegerField(
                        default=2024,
                        validators=[django.core.validators.MinValueValidator(2024)],
                    ),
                ),
                ("major", models.CharField(max_length=2048)),
            ],
        ),
    ]
